---
# tasks file for ansible-nifi

- name: ensure required packages are installed
  yum:
    name: "{{ packages }}"
    state: present
  become: yes

- name: Download binary
  unarchive:
    src: "{{ download_url }}"
    dest: /opt
    remote_src: yes

- name: Create sym link
  file:
    src: "/opt/nifi-{{ nifi_version }}"
    dest: /opt/nifi-current
    state: link

- name: Drop service file
  template:
    src: nifi.service.j2
    dest: /etc/systemd/system/nifi.service
    mode: 0644
    owner: root
    group: root
  register: service_file

- name: Daemon reload
  systemd:
    daemon_reload: true
  when: service_file.changed
