---
# tasks file for ansible-nifi

- name: ensure required packages are installed
  yum:
    name: "{{ packages }}"
    state: present
  become: yes

- name: Download binary
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/nifi.tar.gz

- name: unpack tar
  unarchive:
    src: /tmp/nifi.tar.gz
    dest: /opt
  become: yes

- name: remote tar
  file:
    path: /tmp/nifi.tar.gz
    state: absent

- name: Create sym link
  file:
    src: "/opt/nifi-{{ nifi_version }}"
    dest: /opt/nifi-current
    state: link
  become: yes

- name: Drop service file
  template:
    src: nifi.service.j2
    dest: /etc/systemd/system/nifi.service
    mode: 0644
    owner: root
    group: root
  register: service_file
  become: yes

- name: Daemon reload
  systemd:
    daemon_reload: true
  when: service_file.changed
  become: yes
